package org.example.tokenizer;

public enum JSONTokens {
    TOKEN_OPEN_CURLYBRACKET,
    TOKEN_CLOSE_CURLYBRACKET,
    TOKEN_STRING,
    TOKEN_NUMBER,
    TOKEN_NULL,
    TOKEN_BOOLEAN,
    TOKEN_OPEN_SQUAREBRACKET,
    TOKEN_CLOSE_SQUAREBRACKET,
    TOKEN_COMMA,
    TOKEN_COLON
}
